### ISSUE TITLE
Unresolved reference findNavController()

### ISSUE THREAD

**Issue by IgorGanapolsky** [mitrejcevski/jetpack-playground#1]
Hello,
in Notifications.kt I get a compilation error on line 27:
> Unresolved reference: findNavController()

Any ideas?

**Comment by mitrejcevski** [comment]
Hi, sorry for the late reply. The dependencies I am using are from the very first alpha release, and some of the APIs did change also. I will have to update the dependencies and see what's new there. Feel free to send a PR if you did so already. Thanks!

**Comment by IgorGanapolsky** [comment]
I created the PR 😄
